package customExceptions;

import java.util.*;

public class ThrowException {
	
	public static void main(String []args) {
		throwException();
	}
	
	public static void throwException(){
		try {
			int ind = 7;
			int[] intArr = {1,2,4};
			
			if(ind < 0 || ind > intArr.length) {
				throw new ExtendedArrayException("Selected item is not within the collection.");
			}
		}catch(ExtendedArrayException e) {
			System.out.println(e.getMessage());
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("Java API Array index exception.");
		}
	}
}

