package customExceptions;

import java.util.*;

public class ThrowException {
	
	public static void main(String []args) {
		throwException();
	}
	
	public static void throwException(){
		try {
			
			int[] intArr = {1,2,4};
			
			int num = intArr[5];
			System.out.println("Num: "+ num);
			
		}catch(ExtendedArrayException e) {
			System.out.println(e.getMessage());
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("Java API Array index exception.");
		}
	}
}

